sudo: required

services:
  - docker
  
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install jq
  - chmod u+x build.sh
  - chmod u+x create_hassio_addon.sh

env:
  - ADDON=appdaemon
  - ADDON=appdaemon_dev
script:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
  - ./build.sh "$ADDON"

